# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.6.25.9
    hooks:
      - id: actionlint
        additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
        # actionlint has built in support for pyflakes and shellcheck, sadly they will not be auto updated. Alternatively:
        # args: [-shellcheck=/path/shellcheck -pyflakes=/path/pyflakes]
        # note - invalid path in arguments will fail silently
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt # native (requires/installs Go to build)
  - repo: https://github.com/sirwart/ripsecrets
    # Detect secrets before they are checked in
    rev: v0.1.6
    hooks:
      - id: ripsecrets
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
  # - repo: https://github.com/mrtazz/checkmake.git
  #   # Or another commit hash or version
  #   rev: 0.2.2
  #   hooks:
  #     # Use this hook to let pre-commit build checkmake in its sandbox
  #     - id: checkmake
  #       # OR Use this hook to use a pre-installed checkmark executable
  #       # -   id: checkmake-system
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3025, --ignore, DL3018]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
